### ISSUE TITLE
The time plan for open-sourcing

### ISSUE THREAD

**Issue by SiyuanHuang95** [HanqingWangAI/Dreamwalker#1]
Hi,

Thanks for your sharing, and quite an interesting paper from the Graph and MCTS perceptive. And I am wondering about the time plan for open-souring.

BTW, I am curious about the quality of PathDreamer, have you tested its limit, like within how distant from the current waypoint can it work smoothly?

**Comment by HanqingWangAI** [comment]
Hi Siyuan,

Thank you for being interested in our work! I am working on tidying up the project repo. The code and checkpoints will be progressively released.

The quality of the synthetic views generated by PathDreamer depends heavily on occlusion. This is due to PathDreamer's mechanism of reprojecting the point cloud and inpainting the guidance image. We found empirically that PathDreamer works well within a single room (e.g. a living room) even when the agent moves 7 steps (about 10 meters) from the original position. However, the quality can degrade when the agent travels between rooms. I tried using [text2room](https://github.com/lukasHoel/text2room) to improve quality and robustness, but the inference was too slow.

**Comment by SiyuanHuang95** [comment]
Hi Hanqing,

thanks for your quick reply, and I am really looking forward to your further updates. 

Since PathDreamer works not optimally for cross-room settings, do you have some specific designs for it? Or since the whole network is trained end2end, other modules will learn some walkaround for this part? BTW, what do you think about the usage for Nerf or SD for the scene generation?

**Comment by HanqingWangAI** [comment]
In this work, we use PathDreamer as an off-the-shelf module and we do not further study the workaround for solving large occlusion. I totally agree that Nerf and Diffusion models are suitable for scene synthesis. For instance, Text2room adopts SD to generate textures. I think the synthesis method for planning needs to balance quality and efficiency. In this way, synthesizing the 3D mesh/pointcloud can be more efficient and view-consistent than directly synthesizing views.

**Comment by SiyuanHuang95** [comment]
Great to have this informative tiny discussion with you.

Thanks for your information and updates!

**Comment by Lr-2002** [comment]
Hello, Thanks for your work using MCTS for target search.
Have you cleaned your code ?It would be appreciated if you could share the code. Thanks again.
